# language: node_js
# node_js:
#  - 12
# before_install:
#  - npm install
# install:
#  - npm start
language: ruby

services:
 - docker

before_install:
 - docker build -t afsan007/express-with-mlab .
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker push afsan007/express-with-mlab
 - docker run afsan007/express-with-mlab
script:
 - echo "everything is good"
