apiVersion: apps/v1
kind: Deployment
metadata:
 creationTimestamp: null
 labels:
  run: app
  app: express-app
 name: express-app
spec:
 replicas: 3
 minReadySeconds: 30
 selector:
  matchLabels:
   run: express-app
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxUnavailable: 1
   maxSurge: 2
 template:
  metadata:
   labels:
    run: express-app
  spec:
   restartPolicy: Always
   containers:
    - image: afsan007/express-with-mlab
      name: express-app
      resources:
       limits:
        cpu: 250m
        memory: 200Mi
      livenessProbe:
       failureThreshold: 3
       initialDelaySeconds: 30
       periodSeconds: 10
       timeoutSeconds: 5
       successThreshold: 1
       httpGet:
        path: /healthz
        port: 3000
      readinessProbe:
       failureThreshold: 3
       initialDelaySeconds: 30
       periodSeconds: 10
       timeoutSeconds: 1
       successThreshold: 1
       httpGet:
        path: /healthz
        port: 3000
      args:
       - '/bin/sh'
       - '-c'
       - |
        npm start
      ports:
       - name: express-app
         containerPort: 3000
         protocol: TCP
      env:
       - name: MLAB_USERNAME
         valueFrom:
          secretKeyRef:
           name: mlab-credential
           key: MLAB_USERNAME

       - name: MLAB_PASSWORD
         valueFrom:
          secretKeyRef:
           name: mlab-credential
           key: MLAB_PASSWORD

       - name: MLAB_URL
         valueFrom:
          secretKeyRef:
           name: mlab-credential
           key: MLAB_URL
