apiVersion: v1
kind: Service
metadata:
 labels:
  run: app-svc
 name: express-app-svc
spec:
 type: NodePort
 ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 31000
 selector:
  app: express-app
